

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: team-prometheus:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080
    env_file:
      - .env
    volumes:
      - ./firebaseKey:/app/firebaseKey:ro
    networks:
      - app-network
    restart: unless-stopped

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - app-network
    restart: unless-stopped
#    volumes:
#      - C:\ProgramData\MySQL\MySQL Server 8.0\Data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge