

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: team-prometheus:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      
    env_file:
      - .env
    volumes:
      - ./firebaseKey:/app/firebaseKey:ro
    networks:
      - app-network
    restart: unless-stopped

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - app-network
    restart: unless-stopped
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge
