name: CI/CD using GitHub Actions & Docker

on:
  push:
    branches: [ "develop" ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set executable permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Login DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build --platform linux/arm64 -t gdm-server .

      - name: Tag Docker image
        run: docker tag gdm-server:latest jinseung0327/gdm-server:latest

      - name: Push to DockerHub
        run: docker push jinseung0327/gdm-server:latest

  deploy:
    needs: ci-cd
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull jinseung0327/gdm-server:latest
      - name: Delete old Docker container
        run: sudo docker system prune -a -f --volumes && sudo docker rm -f gdm-server || true
      - name: Run Docker container
        env:
          NICE_API_KEY: ${{secrets.NICE_API_KEY}}
          DB_URL: ${{secrets.DB_URL}}
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          JWT_ISSUER: ${{secrets.JWT_ISSUER}}
          JWT_KEY: ${{secrets.JWT_KEY}}
          ACCESS_TOKEN_EXPIRE_TIME: ${{secrets.ACCESS_TOKEN_EXPIRE_TIME}}
          REFRESH_TOKEN_EXPIRE_TIME: ${{secrets.REFRESH_TOKEN_EXPIRE_TIME}}
          FIREBASE_KEY_PATH: /app/firebaseKey/firebase-service-account.json
        run: |
          sudo docker run -d \
            -e NICE_API_KEY=$NICE_API_KEY \
            -e DB_URL=$DB_URL \
            -e DB_USERNAME=$DB_USERNAME \
            -e DB_PASSWORD=$DB_PASSWORD \
            -e JWT_ISSUER=$JWT_ISSUER \
            -e JWT_KEY=$JWT_KEY \
            -e ACCESS_TOKEN_EXPIRE_TIME=$ACCESS_TOKEN_EXPIRE_TIME \
            -e REFRESH_TOKEN_EXPIRE_TIME=$REFRESH_TOKEN_EXPIRE_TIME \
            -e FIREBASE_KEY_PATH=$FIREBASE_KEY_PATH \
            -v /app/firebaseKey:/app/firebaseKey \
            -p 8080:8080 --name gdm-server jinseung0327/gdm-server:latest
