name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull ghcr.io/wlstmd/gdm-server:latest

      - name: Delete Old docker container
        run: sudo docker rm -f gdm-server || true

      - name: Run Docker Container
        env:
          DB_URL: ${{secrets.DB_URL}}
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          JWT_ISSUER: ${{secrets.JWT_ISSUER}}
          JWT_KEY: ${{secrets.JWT_KEY}}
          ACCESS_TOKEN_EXPIRE_TIME: ${{secrets.ACCESS_TOKEN_EXPIRE_TIME}}
          REFRESH_TOKEN_EXPIRE_TIME: ${{secrets.REFRESH_TOKEN_EXPIRE_TIME}}
        run: |
          sudo docker run -d \
            -e DB_URL=$DB_URL \
            -e DB_USERNAME=$DB_USERNAME \
            -e DB_PASSWORD=$DB_PASSWORD \
            -e JWT_ISSUER=$JWT_ISSUER \
            -e JWT_KEY=$JWT_KEY \
            -e ACCESS_TOKEN_EXPIRE_TIME=$ACCESS_TOKEN_EXPIRE_TIME \
            -e REFRESH_TOKEN_EXPIRE_TIME=$REFRESH_TOKEN_EXPIRE_TIME \
            -p 8080:8080 --name gdm-server ghcr.io/wlstmd/gdm-server
